name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
          link-to-sdk: true

      - name: Build (debug)
        run: make TARGET=r0s-S901BXXSNGZD7 ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build (release)
        run: make TARGET=r0s-S901BXXSNGZD7 ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }} release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: r0s-S901BXXSNGZD7-build
          path: |
            build/**          # <-- sostituisci con il/i path reali generati dal Makefile
          if-no-files-found: error
